import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-cover bg-center md:bg-fixed"
        style={{ backgroundImage: "url('/rBF.png')" }}
      >
        {children}
      </body>
    </html>
  );
}
